language: go
go:
  - 1.11.x

install:
  - git clone --branch master --depth 1 https://github.com/gohugoio/hugo.git hugo
  - go clean -modcache && go install -ldflags 'all=-w -extldflags "-static"' -tags extended

scrpit:
  - mkdir -p themes/beautifulhugo && git clone https://GitHub.com/halogenica/beautifulhugo.git themes/beautifulhugo
  - hugo --theme beautifulhugo

deploy:
  provider: pages
  skip_cleanup: true
  Github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
