language: go
go:
  - 1.11.x

install:
  - export PATH=$PATH:$HOME/bin
  - bash ./scripts/install-hugo.sh

scrpit:
<<<<<<< HEAD
  - hugo
=======
  - mkdir -p themes/beautifulhugo && git clone https://GitHub.com/halogenica/beautifulhugo.git themes/beautifulhugo
  - hugo --theme beautifulhugo
>>>>>>> a258d56c455fbdb017595e286e71bc682fc0ac35

deploy:
  provider: pagess
  skip_cleanup: true
  Github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
