language: go
go:
  - 1.11.x

install:
  - export PATH=$PATH:$HOME/bin
  - bash ./scripts/install-hugo.sh

scrpit:
  - hugo
  
deploy:
  provider: pagess
  skip_cleanup: true
  Github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
