language: go
go:
  - 1.11.x

install:
  - go get https://github.com/gohugoio/hugo

scrpit:
  - mkdir -p themes/beautifulhugo && git clone https://GitHub.com/halogenica/beautifulhugo.git themes/beautifulhugo
  - hugo --theme beautifulhugo

deploy:
  provider: pages
  skip_cleanup: true
  Github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master
